do $$
declare
  seed_owner_id uuid := '00000000-0000-4000-8000-000000000301';
begin
  insert into auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at
  )
  values (
    '00000000-0000-0000-0000-000000000000',
    seed_owner_id,
    'authenticated',
    'authenticated',
    'phase3-marketplace-seed@partyswami.local',
    null,
    timezone('utc', now()),
    '{"provider":"email","providers":["email"]}'::jsonb,
    '{"full_name":"Phase 3 Marketplace Seed"}'::jsonb,
    timezone('utc', now()),
    timezone('utc', now())
  )
  on conflict (id) do update
  set
    email = excluded.email,
    raw_user_meta_data = excluded.raw_user_meta_data,
    updated_at = timezone('utc', now());

  insert into public.profiles (id, full_name)
  values (seed_owner_id, 'Phase 3 Marketplace Seed')
  on conflict (id) do update
  set
    full_name = excluded.full_name,
    updated_at = timezone('utc', now());
end $$;

insert into public.vendors (
  owner_id,
  business_name,
  slug,
  category,
  city,
  state,
  zip_code,
  service_radius_miles,
  contact_name,
  contact_email,
  contact_phone,
  website_url,
  affiliate_url,
  pricing_model,
  starting_price,
  description,
  portfolio_urls,
  status,
  is_verified
)
values
  (
    '00000000-0000-4000-8000-000000000301',
    'Sugar Moon Bakery',
    'sugar-moon-bakery-austin',
    'Bakery',
    'Austin',
    'TX',
    '78701',
    18,
    'Maya Patel',
    'hello@sugarmoon.example',
    '512-555-0101',
    'https://example.com/sugar-moon',
    null,
    'fixed_packages',
    95,
    'Custom cakes, cupcake towers, and dessert table packages for birthdays, showers, graduations, and polished backyard gatherings. Delivery is available for central Austin events.',
    array['https://example.com/sugar-moon/cakes', 'https://example.com/sugar-moon/dessert-tables'],
    'active',
    true
  ),
  (
    '00000000-0000-4000-8000-000000000301',
    'Neon Hour DJ Co.',
    'neon-hour-dj-co',
    'DJ',
    'Austin',
    'TX',
    '78704',
    30,
    'Leo Martinez',
    'bookings@neonhour.example',
    '512-555-0102',
    'https://example.com/neon-hour',
    null,
    'custom_quotes',
    450,
    'High-energy DJ sets, basic lighting, ceremony audio, and reception sound for birthdays, weddings, pool parties, and corporate celebrations across Austin.',
    array['https://example.com/neon-hour/weddings', 'https://example.com/neon-hour/private-events'],
    'active',
    true
  ),
  (
    '00000000-0000-4000-8000-000000000301',
    'Table Bloom Decor',
    'table-bloom-decor',
    'Decor',
    'Austin',
    'TX',
    '78745',
    22,
    'Camille Brooks',
    'hello@tablebloom.example',
    '512-555-0103',
    'https://example.com/table-bloom',
    null,
    'fixed_packages',
    250,
    'Balloon garlands, table styling, backdrop moments, and themed decor kits for hosts who want a finished look without building every piece from scratch.',
    array['https://example.com/table-bloom/balloons', 'https://example.com/table-bloom/tablescapes'],
    'active',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000301',
    'Hill Country Bites',
    'hill-country-bites',
    'Catering',
    'Dripping Springs',
    'TX',
    '78620',
    40,
    'Nora Ellis',
    'events@hillcountrybites.example',
    '512-555-0104',
    'https://example.com/hill-country-bites',
    null,
    'custom_quotes',
    650,
    'Drop-off catering, grazing boards, brunch spreads, taco bars, and family-style menus for casual luxury parties across Austin and the Hill Country.',
    array['https://example.com/hill-country-bites/menus', 'https://example.com/hill-country-bites/grazing'],
    'active',
    true
  ),
  (
    '00000000-0000-4000-8000-000000000301',
    'Lakeside Loft Events',
    'lakeside-loft-events',
    'Venue',
    'Austin',
    'TX',
    '78702',
    12,
    'Priya Shah',
    'tours@lakesideloft.example',
    '512-555-0105',
    'https://example.com/lakeside-loft',
    null,
    'fixed_packages',
    1200,
    'A flexible indoor-outdoor venue for showers, milestone birthdays, rehearsal dinners, and creative celebrations with room for catering and vendor load-in.',
    array['https://example.com/lakeside-loft/gallery', 'https://example.com/lakeside-loft/floorplans'],
    'active',
    true
  ),
  (
    '00000000-0000-4000-8000-000000000301',
    'Bounce & Bash Rentals',
    'bounce-and-bash-rentals',
    'Rentals',
    'Round Rock',
    'TX',
    '78664',
    35,
    'Chris Nguyen',
    'party@bouncebash.example',
    '512-555-0106',
    'https://example.com/bounce-bash',
    'https://example.com/bounce-bash/shop?ref=party-swami',
    'affiliate_links',
    175,
    'Bounce houses, kids tables, lawn games, coolers, tents, and party rental bundles for family events that need fast setup and easy takedown.',
    array['https://example.com/bounce-bash/inflatables', 'https://example.com/bounce-bash/lawn-games'],
    'active',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000301',
    'Spark Cart Entertainment',
    'spark-cart-entertainment',
    'Entertainment',
    'Cedar Park',
    'TX',
    '78613',
    28,
    'Avery Johnson',
    'hello@sparkcart.example',
    '512-555-0107',
    'https://example.com/spark-cart',
    null,
    'custom_quotes',
    300,
    'Photo booths, face painting, craft stations, and roaming entertainers for children, teens, and family-friendly community celebrations.',
    array['https://example.com/spark-cart/photo-booths', 'https://example.com/spark-cart/kids-parties'],
    'active',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000301',
    'Velvet Fork Supper Club',
    'velvet-fork-supper-club',
    'Catering',
    'Austin',
    'TX',
    '78703',
    16,
    'Elena Rossi',
    'events@velvetfork.example',
    '512-555-0108',
    'https://example.com/velvet-fork',
    null,
    'fixed_packages',
    900,
    'Chef-led dinner party menus, passed bites, and cocktail-hour boards for intimate celebrations where food is the main event.',
    array['https://example.com/velvet-fork/private-dinners', 'https://example.com/velvet-fork/cocktail-hour'],
    'active',
    true
  )
on conflict (slug) do update
set
  owner_id = excluded.owner_id,
  business_name = excluded.business_name,
  category = excluded.category,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  service_radius_miles = excluded.service_radius_miles,
  contact_name = excluded.contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  website_url = excluded.website_url,
  affiliate_url = excluded.affiliate_url,
  pricing_model = excluded.pricing_model,
  starting_price = excluded.starting_price,
  description = excluded.description,
  portfolio_urls = excluded.portfolio_urls,
  status = excluded.status,
  is_verified = excluded.is_verified,
  updated_at = timezone('utc', now());

insert into public.planners (
  owner_id,
  business_name,
  slug,
  city,
  state,
  zip_code,
  service_radius_miles,
  contact_name,
  contact_email,
  contact_phone,
  website_url,
  years_experience,
  certifications,
  consultation_price,
  hourly_rate,
  full_service_minimum,
  bio,
  services,
  availability_note,
  status,
  is_verified
)
values
  (
    '00000000-0000-4000-8000-000000000301',
    'Bright Table Events',
    'bright-table-events',
    'Austin',
    'TX',
    '78701',
    35,
    'Jordan Lee',
    'hello@brighttable.example',
    '512-555-0201',
    'https://example.com/bright-table',
    8,
    'Certified Meeting Professional; specializes in showers, brunches, milestone birthdays, and small weddings.',
    75,
    125,
    2200,
    'Bright Table Events helps busy hosts turn a loose idea into a polished plan, with practical vendor sourcing, clean budgets, and calm day-of execution.',
    array['Consultation', 'Vendor sourcing', 'Budget planning', 'Day-of coordination', 'Full-service planning'],
    'Consultations available Tuesday through Thursday. Weekend events need two weeks notice.',
    'active',
    true
  ),
  (
    '00000000-0000-4000-8000-000000000301',
    'Confetti Compass Planning',
    'confetti-compass-planning',
    'Round Rock',
    'TX',
    '78664',
    30,
    'Sam Rivera',
    'plan@confetticompass.example',
    '512-555-0202',
    'https://example.com/confetti-compass',
    5,
    'Family party specialist with experience in kids birthdays, graduations, and backyard events.',
    45,
    95,
    1250,
    'Confetti Compass Planning focuses on approachable parties that still feel special, helping families choose vendors, build timelines, and stay inside budget.',
    array['Consultation', 'Vendor sourcing', 'Budget planning', 'Day-of coordination'],
    'Evening consults available. Saturday coordination depends on event date.',
    'active',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000301',
    'Luxe Little Moments',
    'luxe-little-moments',
    'Austin',
    'TX',
    '78704',
    20,
    'Renee Carter',
    'hello@luxelittlemoments.example',
    '512-555-0203',
    'https://example.com/luxe-little-moments',
    11,
    'Luxury picnic, proposal, shower, and intimate dinner specialist.',
    95,
    150,
    3000,
    'Luxe Little Moments creates high-touch intimate events with refined vendor lists, visual direction, and hands-on coordination for hosts who want every detail handled.',
    array['Consultation', 'Vendor sourcing', 'Full-service planning'],
    'Full-service bookings are limited to two events per month.',
    'active',
    true
  )
on conflict (slug) do update
set
  owner_id = excluded.owner_id,
  business_name = excluded.business_name,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  service_radius_miles = excluded.service_radius_miles,
  contact_name = excluded.contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  website_url = excluded.website_url,
  years_experience = excluded.years_experience,
  certifications = excluded.certifications,
  consultation_price = excluded.consultation_price,
  hourly_rate = excluded.hourly_rate,
  full_service_minimum = excluded.full_service_minimum,
  bio = excluded.bio,
  services = excluded.services,
  availability_note = excluded.availability_note,
  status = excluded.status,
  is_verified = excluded.is_verified,
  updated_at = timezone('utc', now());
